<?xml version="1.0"?>
<!-- Copyright 2015 Fadri Furrer, ASL, ETH Zurich, Switzerland Copyright 
	2015 Michael Burri, ASL, ETH Zurich, Switzerland Copyright 2015 Mina Kamel, 
	ASL, ETH Zurich, Switzerland Copyright 2015 Janosch Nikolic, ASL, ETH Zurich, 
	Switzerland Copyright 2015 Markus Achtelik, ASL, ETH Zurich, Switzerland 
	Licensed under the Apache License, Version 2.0 (the "License"); you may not 
	use this file except in compliance with the License. You may obtain a copy 
	of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required 
	by applicable law or agreed to in writing, software distributed under the 
	License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS 
	OF ANY KIND, either express or implied. See the License for the specific 
	language governing permissions and limitations under the License. LEADER 
	UAV LEADER UAV LEADER UAV LEADER UAV LEADER UAV -->

<robot name="firefly" xmlns:xacro="http://ros.org/wiki/xacro">
	<xacro:include filename="$(find rotors_description)/urdf/multirotor_base_modified.xacro" />

	<!-- Properties -->
	<!-- xacro:property name="namespace" value="$(arg namespace" /-->
	<xacro:property name="rotor_velocity_slowdown_sim"
		value="10" />
	<xacro:property name="use_mesh_file" value="true" />
	<xacro:property name="mesh_file"
		value="package://rotors_description/meshes/firefly.dae" />
	<xacro:property name="mass" value="1.5" />
	<xacro:property name="body_width" value="0.1" />
	<xacro:property name="body_height" value="0.16" />
	<xacro:property name="mass_rotor" value="0.005" />
	<xacro:property name="arm_length" value="0.215" />
	<xacro:property name="rotor_offset_top" value="0.037" />
	<xacro:property name="radius_rotor" value="0.1" />
	<xacro:property name="motor_constant" value="8.54858e-06" />
	<!-- [kg m/s^2] -->

	<xacro:property name="moment_constant" value="0.016" />
	<xacro:property name="time_constant_up" value="0.0125" />
	<!-- [s] -->

	<xacro:property name="time_constant_down" value="0.025" />
	<!-- [s] -->

	<xacro:property name="max_rot_velocity" value="838" />
	<!-- [rad/s] -->

	<xacro:property name="sin30" value="0.5" />
	<xacro:property name="cos30" value="0.866025403784" />
	<xacro:property name="rotor_drag_coefficient" value="8.06428e-05" />
	<xacro:property name="rolling_moment_coefficient" value="0.000001" />

	<xacro:property name="PI" value="3.1415926535897931" />
	<xacro:property name="masslink" value="0.01" />
	<!-- arbitrary value for mass of the links of the arm -->
	<xacro:property name="width" value="0.005" />
	<!-- Square dimensions (widthxwidth) of beams -->
	<xacro:property name="height1" value="0.05" />
	<!-- Link 1 -->

	<xacro:property name="height2" value="0.05" />
	<!-- Link 2 -->

	<xacro:property name="height3" value="0.05" />
	<!-- Link 3 -->

	<xacro:property name="height4" value="0.03" />
	<!-- Link 3 -->

	<xacro:property name="height5" value="0.03" />
	<!-- Link 3 -->

	<xacro:property name="height6" value="0.03" />
	<!-- Link 3 -->

	<!-- xacro:property name="axel_offset" value="0.005" / -->
	<!-- Space btw top of beam and the each joint -->

	<!-- Property Blocks -->
	<xacro:property name="body_inertia">
		<inertia ixx="0.0347563" ixy="0.0" ixz="0.0" iyy="0.0458929"
			iyz="0.0" izz="0.0977" />
		<!-- [kg m^2] [kg m^2] [kg m^2] [kg m^2] [kg m^2] [kg m^2] -->
	</xacro:property>

	<!-- inertia of a single rotor, assuming it is a cuboid. Height=3mm, width=15mm -->
	<xacro:property name="rotor_inertia">
		<xacro:box_inertia x="${radius_rotor}" y="0.015" z="0.003"
			mass="${mass_rotor*rotor_velocity_slowdown_sim}" />
	</xacro:property>

	<xacro:macro name="firefly"
		params="namespace mav_name ox oy oz ophi otheta opsi m0 m1 m2 m3 m4 m5"
		xmlns:xacro="http://ros.org/wiki/xacro">
		<!-- Included URDF Files -->
		<!-- 
		<origin xyz="${ox} ${oy} ${oz}" rpy="${ophi} ${otheta} ${opsi}" />
		-->

		<!-- Instantiate multirotor_base_macro once -->
		<xacro:multirotor_base_macro
			robot_namespace="${namespace}" robot_name="${mav_name}" mass="${mass}" body_width="${body_width}"
			body_height="${body_height}" use_mesh_file="${use_mesh_file}"
			mesh_file="${mesh_file}">
			<xacro:insert_block name="body_inertia" />
		</xacro:multirotor_base_macro>

		<!-- Instantiate rotors -->
		<xacro:vertical_rotor robot_namespace="${namespace}" robot_name="${mav_name}" 
			suffix="front_left" direction="ccw" motor_constant="${motor_constant}"
			moment_constant="${moment_constant}" parent="${namespace}/${mav_name}/base_link"
			mass_rotor="${mass_rotor}" radius_rotor="${radius_rotor}"
			time_constant_up="${time_constant_up}" time_constant_down="${time_constant_down}"
			max_rot_velocity="${max_rot_velocity}" motor_number="${m0}"
			rotor_drag_coefficient="${rotor_drag_coefficient}"
			rolling_moment_coefficient="${rolling_moment_coefficient}" color="Red"
			use_own_mesh="false" mesh="">
			<origin xyz="${cos30*arm_length} ${sin30*arm_length} ${rotor_offset_top}"
				rpy="0 0
			0" />
			<xacro:insert_block name="rotor_inertia" />
		</xacro:vertical_rotor>

		<xacro:vertical_rotor robot_namespace="${namespace}" robot_name="${mav_name}" 
			suffix="left" direction="cw" motor_constant="${motor_constant}"
			moment_constant="${moment_constant}" parent="${namespace}/${mav_name}/base_link"
			mass_rotor="${mass_rotor}" radius_rotor="${radius_rotor}"
			time_constant_up="${time_constant_up}" time_constant_down="${time_constant_down}"
			max_rot_velocity="${max_rot_velocity}" motor_number="${m1}"
			rotor_drag_coefficient="${rotor_drag_coefficient}"
			rolling_moment_coefficient="${rolling_moment_coefficient}" color="Blue"
			use_own_mesh="false" mesh="">
			<origin xyz="0 ${arm_length} ${rotor_offset_top}" rpy="0 0 0" />
			<xacro:insert_block name="rotor_inertia" />
		</xacro:vertical_rotor>

		<xacro:vertical_rotor robot_namespace="${namespace}" robot_name="${mav_name}" 
			suffix="back_left" direction="ccw" motor_constant="${motor_constant}"
			moment_constant="${moment_constant}" parent="${namespace}/${mav_name}/base_link"
			mass_rotor="${mass_rotor}" radius_rotor="${radius_rotor}"
			time_constant_up="${time_constant_up}" time_constant_down="${time_constant_down}"
			max_rot_velocity="${max_rot_velocity}" motor_number="${m2}"
			rotor_drag_coefficient="${rotor_drag_coefficient}"
			rolling_moment_coefficient="${rolling_moment_coefficient}" color="Blue"
			use_own_mesh="false" mesh="">
			<origin
				xyz="-${cos30*arm_length} ${sin30*arm_length} ${rotor_offset_top}"
				rpy="0
			0 0" />
			<xacro:insert_block name="rotor_inertia" />
		</xacro:vertical_rotor>

		<xacro:vertical_rotor robot_namespace="${namespace}" robot_name="${mav_name}" 
			suffix="back_right" direction="cw" motor_constant="${motor_constant}"
			moment_constant="${moment_constant}" parent="${namespace}/${mav_name}/base_link"
			mass_rotor="${mass_rotor}" radius_rotor="${radius_rotor}"
			time_constant_up="${time_constant_up}" time_constant_down="${time_constant_down}"
			max_rot_velocity="${max_rot_velocity}" motor_number="${m3}"
			rotor_drag_coefficient="${rotor_drag_coefficient}"
			rolling_moment_coefficient="${rolling_moment_coefficient}" color="Blue"
			use_own_mesh="false" mesh="">
			<origin
				xyz="-${cos30*arm_length} -${sin30*arm_length} ${rotor_offset_top}"
				rpy="0
			0 0" />
			<xacro:insert_block name="rotor_inertia" />
		</xacro:vertical_rotor>

		<xacro:vertical_rotor robot_namespace="${namespace}" robot_name="${mav_name}" 
			suffix="right" direction="ccw" motor_constant="${motor_constant}"
			moment_constant="${moment_constant}" parent="${namespace}/${mav_name}/base_link"
			mass_rotor="${mass_rotor}" radius_rotor="${radius_rotor}"
			time_constant_up="${time_constant_up}" time_constant_down="${time_constant_down}"
			max_rot_velocity="${max_rot_velocity}" motor_number="${m4}"
			rotor_drag_coefficient="${rotor_drag_coefficient}"
			rolling_moment_coefficient="${rolling_moment_coefficient}" color="Blue"
			use_own_mesh="false" mesh="">
			<origin xyz="0 -${arm_length} ${rotor_offset_top}" rpy="0 0 0" />
			<xacro:insert_block name="rotor_inertia" />
		</xacro:vertical_rotor>

		<xacro:vertical_rotor robot_namespace="${namespace}" robot_name="${mav_name}" 
			suffix="front_right" direction="cw" motor_constant="${motor_constant}"
			moment_constant="${moment_constant}" parent="${namespace}/${mav_name}/base_link"
			mass_rotor="${mass_rotor}" radius_rotor="${radius_rotor}"
			time_constant_up="${time_constant_up}" time_constant_down="${time_constant_down}"
			max_rot_velocity="${max_rot_velocity}" motor_number="${m5}"
			rotor_drag_coefficient="${rotor_drag_coefficient}"
			rolling_moment_coefficient="${rolling_moment_coefficient}" color="Red"
			use_own_mesh="false" mesh="">
			<origin
				xyz="${cos30*arm_length} -${sin30*arm_length} ${rotor_offset_top}"
				rpy="0
			0 0" />
			<xacro:insert_block name="rotor_inertia" />
		</xacro:vertical_rotor>

	</xacro:macro>
</robot>
