<?xml version="1.0"?>
<!--
  Copyright 2015 Fadri Furrer, ASL, ETH Zurich, Switzerland
  Copyright 2015 Michael Burri, ASL, ETH Zurich, Switzerland
  Copyright 2015 Mina Kamel, ASL, ETH Zurich, Switzerland
  Copyright 2015 Janosch Nikolic, ASL, ETH Zurich, Switzerland
  Copyright 2015 Markus Achtelik, ASL, ETH Zurich, Switzerland

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<robot name="firefly" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Properties -->
  <xacro:property name="namespace" value="$(arg mav_name)" />
  <xacro:property name="rotor_velocity_slowdown_sim" value="10" />
  <xacro:property name="use_mesh_file" value="true" />
  <xacro:property name="mesh_file" value="package://rotors_description/meshes/firefly.dae" />
  <xacro:property name="mass" value="1.5" /> <!-- [kg] -->
  <xacro:property name="body_width" value="0.1" /> <!-- [m] -->
  <xacro:property name="body_height" value="0.16" /> <!-- [m] -->
  <xacro:property name="mass_rotor" value="0.005" /> <!-- [kg] -->
  <xacro:property name="arm_length" value="0.215" /> <!-- [m] -->
  <xacro:property name="rotor_offset_top" value="0.037" /> <!-- [m] -->
  <xacro:property name="radius_rotor" value="0.1" /> <!-- [m] -->
  <xacro:property name="motor_constant" value="8.54858e-06" /> <!-- [kg m/s^2] -->
  <xacro:property name="moment_constant" value="0.016" /> <!-- [m] -->
  <xacro:property name="time_constant_up" value="0.0125" /> <!-- [s] -->
  <xacro:property name="time_constant_down" value="0.025" /> <!-- [s] -->
  <xacro:property name="max_rot_velocity" value="838" /> <!-- [rad/s] -->
  <xacro:property name="sin30" value="0.5" />
  <xacro:property name="cos30" value="0.866025403784" />
  <xacro:property name="rotor_drag_coefficient" value="8.06428e-05" />
  <xacro:property name="rolling_moment_coefficient" value="0.000001" />

<xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="masslink" value="0.01" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.01" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="0.2" /> <!-- Link 1 -->
  <xacro:property name="height2" value="0.1" /> <!-- Link 2 -->
  <xacro:property name="height3" value="0.1" /> <!-- Link 3 -->
  <xacro:property name="camera_link" value="0.005" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.005" /> <!-- Space btw top of beam and the each joint -->



  
<!-- ARM MODEL BELOW -->
<joint name="fixed" type="fixed">
    <parent link="firefly/link3"/>
    <child link="${namespace}/linkbase"/>
  </joint>

  <!-- Base Link -->
  <link name="${namespace}/linkbase">
    <collision>
      <origin xyz="0.1 0.0 -0.03" rpy="0.0 0.0 0.0"/>
      <geometry>
	<box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0.1 0.0 -0.03" rpy="0.0 0.0 0.0"/>
      <geometry>
	<box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0.1 0.0 -0.03" rpy="0.0 0.0 0.0"/>
      <mass value="${masslink}"/>
      <inertia
	  ixx="${masslink / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${masslink / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${masslink / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>


<joint name="joint1" type="continuous">
    <parent link="${namespace}/linkbase"/>
    <child link="${namespace}/link2"/>
    <origin xyz="0.1 ${width} -${0.03+height1/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0"/>
  </joint>

  <!-- Middle Link -->
  <link name="${namespace}/link2">
    <collision>
      <origin xyz="0 0 -${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 -${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 -${height2/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${masslink}"/>
      <inertia
	  ixx="${masslink / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
	  iyy="${masslink / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
	  izz="${masslink / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>
  

<joint name="joint2" type="continuous">
    <parent link="${namespace}/link2"/>
    <child link="${namespace}/link3"/>
    <origin xyz="0 -${width} -${height2-axel_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0"/>
  </joint>

  <!-- Top Link -->
  <link name="${namespace}/link3">
    <collision>
      <origin xyz="0 0 -${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height3}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 -${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height3}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 -${height3/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${masslink}"/>
      <inertia
	  ixx="${masslink / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
	  iyy="${masslink / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
	  izz="${masslink / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>


  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
<hardwareInterface>EffortJointInterface</hardwareInterface>
      <!--hardwareInterface>PositionJointInterface</hardwareInterface-->
    </joint>
    <actuator name="motor11">
<hardwareInterface>EffortJointInterface</hardwareInterface>
      <!--hardwareInterface>PositionJointInterface</hardwareInterface-->
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
<hardwareInterface>EffortJointInterface</hardwareInterface>
      <!--hardwareInterface>PositionJointInterface</hardwareInterface-->
    </joint>
    <actuator name="motor12">
 <hardwareInterface>EffortJointInterface</hardwareInterface>
      <!--hardwareInterface>PositionJointInterface</hardwareInterface-->
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
<robotNamespace>/$(arg mav_name)</robotNamespace>
    </plugin>
  </gazebo>


</robot>
